export default {
  avatar                   : require('./images/avatar.png'),
  algorithmsWillDistribute : require('./images/algorithms_will_distribute.png'),
  everyCollaborator        : require('./images/every_collaborator.png'),
  everyCollaboratorNoBg    : require('./images/every_collaborator_no_bg.png'),
  euFlag                   : require('./images/eu_flag.jpg'),
  avatarOne                : require('./images/avatars/1.png'),
  logo                     : require('./images/logo.png'),
  logoIcon                 : require('./images/logo_icon.svg'),
  collaborateHero          : require('./images/collaborate_hero.png'),
  greatScores              : require('./images/great_scores.png'),
  mahlerSymphony           : require('./images/mahler_symphony.png'),
  partnerGoldsmiths        : require('./images/partners/goldsmiths.png'),
  partnerMdw               : require('./images/partners/mdw.png'),
  partnerMuziekweb         : require('./images/partners/muziekweb.png'),
  partnerPeachnote         : require('./images/partners/peachnote.png'),
  partnerRco               : require('./images/partners/rco.png'),
  partnerTuDelft           : require('./images/partners/tu_delft.png'),
  partnerUpfMtg            : require('./images/partners/upf_mtg.png'),
  partnerUpfTide           : require('./images/partners/upf_tide.png'),
  partnerVideodock         : require('./images/partners/videodock.png'),
  partnerVoctroLabs        : require('./images/partners/voctro_labs.png'),
  pickAScore               : require('./images/pick_a_score.png'),
  supportedBy              : require('./images/supported_by.png'),
  unlockClassics           : require('./images/unlock_classics.png'),
  personTrumpetStandingLeft: require('./images/personTrumpetStandingLeft.png'),
  personStandingRight      : require('./images/personStandingRight.png'),
};

